In [1]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [ ]:
!pip install opencv-python --user

  Using cached opencv_python-4.3.0.36-cp37-cp37m-manylinux2014_x86_64.whl (43.7 MB)


In [15]:
!pip uninstall -y opencv-python

In [7]:
!pip install fontconfig

     |████████████████████████████████| 121 kB 947 kB/s eta 0:00:01
    ERROR: Command errored out with exit status 1:
     command: /home/bitai/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y1v8v7a4/fontconfig/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y1v8v7a4/fontconfig/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-y1v8v7a4/fontconfig/pip-egg-info
         cwd: /tmp/pip-install-y1v8v7a4/fontconfig/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y1v8v7a4/fontconfig/setup.py", line 9
        exec line in glb
                ^
    SyntaxError: Missing parentheses in call to 'exec'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python 

In [ ]:
!pip install opencv-python --user

In [1]:
import cv2

In [2]:
print(cv2.__version__)

4.3.0


In [3]:
import numpy as np

In [116]:
img = np.random.randint(0, 10, (7, 7))
print(img)
print(type(img))

[[6 4 9 8 6 8 8]
 [0 7 4 9 4 5 1]
 [7 9 0 8 6 6 5]
 [3 1 5 7 8 4 3]
 [4 1 3 8 0 1 6]
 [6 8 7 2 1 7 1]
 [7 1 1 9 8 9 3]]
<class 'numpy.ndarray'>


In [6]:
img_np = np.ones([7, 7])

print(img_np)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [7]:
kernel = np.array([1, 0, -1])

print(kernel)

[ 1  0 -1]


In [8]:
print(type(kernel))
print(type(img_np))

# 영상처리에서 사용하는 컨벌트에서는 불가함.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
img_cv = cv2.resize(img_np, (7, 7))
print(img_cv)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [12]:
kernel = cv2.resize(kernel, (1, 3))
print(kernel)

[[ 1]
 [ 0]
 [-1]]


In [13]:
print(type(img_cv))
print(type(kernel))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

# 1행렬에 convolution을 하면 0이 된다!

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [18]:
print(kernel)

[[ 1]
 [ 0]
 [-1]]


In [17]:
print(img_cv)

[[0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 3.]]


In [16]:
img_cv[0][0] = 0
img_cv[3][3] = 2
img_cv[6][6] = 3


# filter2D - Convolution이 결국 라플라스 변환과 푸리에 변환에 관계를 가지고 있기 때문
# Convolution을 통해서 필터를 할 수 있기 때문!
conv_test = cv2.filter2D(img_cv, -1, kernel)
print(conv_test)



# 이름이 convolution이 아니고 filter2D라고 되어있음
# filter는 뭔가를 거르는 것!! 
# convolution을 하는데 왜 걸러질까?
# 프리에 트렌스폼과 convolution이 어떤 관계를 가지고 있음!

# 프리에트렌스폼은 스펙트럼 분석을 함.
# 스펙트럼 분석을 하면 주파수가 나옴. --> 해당 신호 주파수를 분류할 수 있음.
# 스펙트럼은 결국 어떤 영상 성분이 어떤 주파수를 가지고 있다는 얘기!
# 무선 신호, 음성 신호 처리할 떄 우리가 말하는 주파수가 4000~7000Hrz
# 무슨 말, 어떤 얘기 하는지 분석하려면 스펙트럼 분석해야 함.

# 육안으로는 알 수 없으니까 어떤 주파수 대의 성분이 있는지 파악을 하는 것.

# 필터 자체를 할 때는 라플라스 트랜스폼
# 컴벌루션을 하면 필터링을 하면서 적정한 스펙트럼을 제거할 수 있음


[[ 0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [19]:
# filter2D 역할을 하는 함수를 만들어보자!


In [ ]:
# 라플라스 변환 => 전달 함수를 얻기 위해 계산함
# 입력 대 출력비를 구하겠다.
# 입력이 10, 출려기 7, 입출력비 : 7/10 = 0.7
# 입력이 y'' = y' + 3y + 2
# 출력이 y' = 3e^3x
# 라플라스 변환 통해 입출력비를 계산할 수 있게 된다.
# integral 0 ~ inf f(t)e^st dt

# 1계 미분 방정식(RC 회로)
# 라플라스 변환, 푸리에 변환 약식
# Low Pass Filter(LPF 설계법) - 1D Convolution
# 전달함수 -> 실제 값을 필터링 하는 방법

In [12]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [107]:
# 이미지 분류해보기

classifier = Sequential()
classifier.add(
    Conv2D(
        32, (3, 3), 
        input_shape = (64, 64, 3), 
        activation = 'relu'
    )
)


classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(Flatten())

# 컨벌루션 하는 네트워크는 tensor를 쓰는 구나!
# 회귀분석은 단순 행렬연산!!
# 결과보면 tensor로 나옴!!
# 2D convolution보면 tensor쓰는 것을 알 수 있음.


# 다시~~
# MaxPool2D : 최대 풀링!!!
#

In [108]:
classifier.summary()
# 다시~
# flatten (Flatten)            (None, 30752)           
# 를 보면 플래트닝을 통해 1차원으로 만들어준 것!

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_23 (Conv2D)           (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_19 (MaxPooling (None, 31, 31, 32)        0         
_________________________________________________________________
flatten_7 (Flatten)          (None, 30752)             0         
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________


In [109]:
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(64, activation = 'relu')
)
classifier.add(
    Dense(32, activation = 'relu')
)
classifier.add(
    Dense(16, activation = 'relu')
)
classifier.add(
    Dense(1, activation = 'sigmoid')
)
classifier.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [110]:
from keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(
    rescale = 1.0 / 255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)

test_gen = ImageDataGenerator(rescale = 1.0 / 255)

In [111]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set

cats  dogs


In [112]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/test_set

cats  dogs


In [113]:
trainSet = train_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set',
    target_size = (64, 64), # 위에 만들었던 네트워크도 64, 64로 만들었고, 실제 이미지도 64, 64이기 때문!!
    batch_size = 32,
    class_mode = 'binary'
)

testSet = train_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/test_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)

Found 20000 images belonging to 2 classes.
Found 5000 images belonging to 2 classes.


In [117]:
# fit  ->  다시

batch_size = 100

classifier.fit_generator(
    trainSet,
    steps_per_epoch = int(10000/batch_size),
    epochs = 100,
    validation_data = testSet,
    validation_steps = int(2500/batch_size)
)

Epoch 1/100
100/100 [==============================] - 10s 99ms/step - loss: 0.5437 - accuracy: 0.7216 - val_loss: 0.5399 - val_accuracy: 0.7175
Epoch 2/100
100/100 [==============================] - 10s 96ms/step - loss: 0.5509 - accuracy: 0.7175 - val_loss: 0.5450 - val_accuracy: 0.7200
Epoch 3/100
100/100 [==============================] - 10s 96ms/step - loss: 0.5494 - accuracy: 0.7128 - val_loss: 0.5267 - val_accuracy: 0.7475
Epoch 4/100
100/100 [==============================] - 10s 97ms/step - loss: 0.5616 - accuracy: 0.6941 - val_loss: 0.5858 - val_accuracy: 0.6975
Epoch 5/100
100/100 [==============================] - 10s 98ms/step - loss: 0.5280 - accuracy: 0.7347 - val_loss: 0.5679 - val_accuracy: 0.7075
Epoch 6/100
100/100 [==============================] - 10s 97ms/step - loss: 0.5225 - accuracy: 0.7403 - val_loss: 0.5466 - val_accuracy: 0.7287
Epoch 7/100
100/100 [==============================] - 10s 100ms/step - loss: 0.5386 - accuracy: 0.7231 - val_loss: 0.5184 - val_a

100/100 [==============================] - 10s 97ms/step - loss: 0.4320 - accuracy: 0.8003 - val_loss: 0.4799 - val_accuracy: 0.7638
Epoch 58/100
100/100 [==============================] - 10s 96ms/step - loss: 0.4181 - accuracy: 0.8009 - val_loss: 0.5230 - val_accuracy: 0.7525
Epoch 59/100
100/100 [==============================] - 10s 96ms/step - loss: 0.4139 - accuracy: 0.8028 - val_loss: 0.5138 - val_accuracy: 0.7675
Epoch 60/100
100/100 [==============================] - 10s 97ms/step - loss: 0.4106 - accuracy: 0.8106 - val_loss: 0.5529 - val_accuracy: 0.7462
Epoch 61/100
100/100 [==============================] - 10s 97ms/step - loss: 0.4170 - accuracy: 0.8094 - val_loss: 0.5123 - val_accuracy: 0.7362
Epoch 62/100
100/100 [==============================] - 10s 96ms/step - loss: 0.4215 - accuracy: 0.8012 - val_loss: 0.5287 - val_accuracy: 0.7425
Epoch 63/100
100/100 [==============================] - 10s 96ms/step - loss: 0.4259 - accuracy: 0.8050 - val_loss: 0.5220 - val_accuracy

In [118]:
import numpy as np

from keras.preprocessing import image

In [119]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets

 dataset  'test images'


In [120]:
new_image = image.load_img(
    'Applied-Deep-Learning-with-Keras/Lesson07/Datasets/test images/test_image_2.jpg',
    target_size = (64, 64)
)

In [121]:
new_image = image.img_to_array(new_image)
new_image = np.expand_dims(new_image, axis = 0)

result = classifier.predict(new_image)
#trainSet.class_indices

if result[0][0] == 1:
    prediction = 'Dog'
else:
    prediction = 'Cat'
    
print(prediction)

# convolution 네트워크는 특정 물체 판별하는 인공지는 네트워크

Cat
