In [1]:
# p.88

import numpy as np

vec1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vec1)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
# 이 방식이 조금 더 편함!
vec1 = np.arange(1, 11)

print(vec1)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
mat1 = np.array([
    [1,   2,  3],
    [4,   5,  6],
    [7,   8,  9],
    [10, 11, 12]
])

print(mat1)
print(mat1.shape) # 4행 3열의 행렬이라는 것을 알 수 있음.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [5]:
mat2 = np.matrix([
    [1,   2,  3],
    [4,   5,  6],
    [7,   8,  9],
    [10, 11, 12]
])

print(mat2)
print(mat2.shape)

# 위와 결과 동일
# mat1, mat2가 만들기 좀 번거로움.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [6]:
# 행렬 안에 행렬이 들어 있는 느낌
ten1 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]],
        
        [[7, 8, 9],
        [10, 11, 12]
    ]
])

print(ten1)
print(ten1.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [7]:
mat3 = mat1 + mat2
print(mat3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [9]:
mat4 = mat1 * mat2
print(mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [12]:
mat3 = np.array([
    [1,   2,  3],
    [4,   5,  6],
    [7,   8,  9],
])

print(mat3)
print(mat3.shape) 

mat4 = np.matrix([
    [4,   5,  6],
    [7,   8,  9],
    [10, 11, 12]
])

print(mat4)
print(mat4.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(3, 3)


In [13]:
mat5 = mat3 * mat4
print(mat5)

[[ 48  54  60]
 [111 126 141]
 [174 198 222]]


In [ ]:
# 행렬 연산의 규칙
# 행렬의 행과 열로 구성된다.
# 행렬의 곱셈을 수행하기 위한 최소한의 규칙
# m by n 행렬을 곱하려면 n by x가 되어야 한다.
# 두 행렬의 곱셈 결과는 m by x가 된다.

In [14]:
mat5 = mat1 * mat2

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [41]:
# 전치 행렬 = 행과 열의 위치를 바꾼다.
print(mat1.T) 
print(mat1)
print(mat1.T.shape) # 행렬의 사이즈가 바뀜
print(mat1.shape)

[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(2, 2, 3)
(3, 2, 2)


In [16]:
# 3 by 4 * 4 by 3 => 3 by 3
mat5 = mat1.T * mat2
print(mat5)

# 케라스 쓰면서 많이 실수하는 것은?
# 자꾸 오류 메세지로 차원이 안맞는다고 뜨는데 왜 그렇지?
# convolution도 행렬 연산인데, 행렬 연산을 할 때 size 안맞는걸 행렬 연산하면
# 자꾸 오류가 뜨는 것!
# 행렬 연산에는 위와 같이 규칙을 지켜줘야 함.

# 166 =  1*1 + ~~~ 다시~~

[[166 188 210]
 [188 214 240]
 [210 240 270]]


In [17]:
# 4 by 3 * 3 by 4 => 4 by 4
mat5 = mat1 * mat2.T
print(mat5)

[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]


In [18]:
print(vec1.shape)
# 1차원 10개 있음

(10,)


In [19]:
# 위의 예제들을 스마트하게 만들어보기!
# 행렬 쉽게 만들기

# np.arange(0, 11, 2) 시작이 0 ~ 11까지 2씩 증가, 
# reshape((2, 3) : 행 2, 열 3으로 만들자!
smartMat = np.arange(0, 11, 2).reshape((2, 3))

print(smartMat)
print(smartMat.shape)


[[ 0  2  4]
 [ 6  8 10]]
(2, 3)


In [20]:
# 전체 행렬에 4를 더한 형태
# 행렬에 스칼라 더한 형태
test = mat1 + 4

print(test)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [21]:
smartMat2 = np.arange(1, 13).reshape((3, 4))

print(smartMat2)
print(smartMat2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [24]:
print(len(mat1))

4


In [25]:
# 차원 변환이 필요한 경우가 있음 - 가우스-조르단 소거법

# 행렬을 1차원 벡터로 변환해야할 경우가 있음 
# -> 가우스 - 조르단 소거법을 사용해야 할 때 
# -> 어떤 선들이 여러 개 있을 때 그 선들의 교차성분을 찾으려고 할 때는 그들의 연립방정식을 계산해서 x,y (,z) 값을 찾아야 함.
# >>> 그 성분을 연립방정식을 만족시키면서 뽑아내야 할 때,
#     식이 10개라면 10원 연립방정식은 너무 어렵기 때문에 가우스-조르단 소거법을 사용!
# 4 by 3 행렬을 1차원 벡터로 변환!
mat1 = mat1.reshape(mat1.shape[0] * mat1.shape[1])

print(mat1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
print(mat2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
# 텐서 만들기

# 텐서를 해석하는 방법 (다중 배열과 동일)
# 맨 앞의 숫자가 큰 집합의 개수를 의미함
# 뒤쪽의 2개는 행렬의 모양을 의미
# 즉 뒤쪽에 2개를 통해 행렬의 모양을 잡고
# 맨 앞의 숫자를 통해 해당 행렬이 몇 개 있는지 파악하면 된다.


# 3개의 큰 행렬 집합이 있고, 2 by 2 행렬들이 들어 있음.
ten2 = mat1.reshape((3, 2, 2))

print(ten2)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [48]:
# 계산하기 편하려면 편한 숫자로 잡아보자!
# 타입을 바꿔서 출력
ret = np.matrix(np.arange(1, 7)). reshape((2, 3))

ten3 = np.array([
    ret, ret
]) 

print(ten3)
print(ten3.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [50]:
ret2 = np.matrix(np.arange(2, 8)).reshape((2, 3))

ten33 = np.array([
    ret, ret2
]) 

print(ten33)

[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]]


In [36]:
# 텐서 간의 연산을 하기 위해 차원 맞추기

print(ten3.T)
print(ten3.T.shape)

# [[[1 1]
#  [4 4]]
# 특정한 지점의 픽셀 값

# [[2 2]
#  [5 5]]
# 그 다음 장면에서의 해당 위치의 픽셀 값

[[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]
(3, 2, 2)


In [42]:
# 텐서 연산
# 텐서는 곱셈으로 표현할 수가 없음.

# 왜?
# 상대성 이론을 만들기 위해 도입된 수학이 텐서
# 텐서 도트연산, 크로스연산, 사이클링 연산
# 벡터 >> 내적(토트 프로덕트), 외적(크로스 프로덕트) 
# 텐서에서도 dot product, cross product 구현 가능!
# 대신 cross product 구현하려면 사이클링 연산을 구현해야 함.
# 사이클링 연산은 보통 잘 안씀

# 일반적으로는 dot product를 주로 사용.

# 그래서 텐서의 연산은 dot()을 사용!!
ten4 = ten3.dot(ten2)
# >>> 에러 남

ValueError: shapes (2,2,3) and (3,2,2) not aligned: 3 (dim 2) != 2 (dim 1)

In [53]:
print(ten2.shape)
print(ten3.shape)

(3, 2, 2)
(2, 2, 3)


In [54]:
# [[[ 1  2]   [[[1 2 3]
#   [ 3  4]]    [4 5 6]]
#             [[1 2 3]
#               [4 5 6]]]

# [[ 5  6]
#  [ 7  8]]

# [[ 9 10]
#  [11 12]]]

ten4 = ten2.dot(ten3)
print(ten4)
print(ten4.shape)
# p.84에서
# convolutin network가 바로 이런 연산을 따라감!

# 이 경우는 2 by 3 짜리가 6개 생기는 구조여서 
# 이렇게 구성되도록 텐서 연산하면 안되고
# (x, 2, 2) or (x, 3, 3)이런식으로 맞춰줘야 함

[[[[  9  12  15]
   [  9  12  15]]

  [[ 19  26  33]
   [ 19  26  33]]]


 [[[ 29  40  51]
   [ 29  40  51]]

  [[ 39  54  69]
   [ 39  54  69]]]


 [[[ 49  68  87]
   [ 49  68  87]]

  [[ 59  82 105]
   [ 59  82 105]]]]
(3, 2, 2, 3)


In [55]:
# [[[ 1  2]   [[[1 2 3]
#   [ 3  4]]    [4 5 6]]
#              [[2 3 4]
#               [5 6 7]]]

# [[ 5  6]
#  [ 7  8]]

# [[ 9 10]
#  [11 12]]]

ten44 = ten2.dot(ten33)
print(ten44)
print(ten44.shape)

[[[[  9  12  15]
   [ 12  15  18]]

  [[ 19  26  33]
   [ 26  33  40]]]


 [[[ 29  40  51]
   [ 40  51  62]]

  [[ 39  54  69]
   [ 54  69  84]]]


 [[[ 49  68  87]
   [ 68  87 106]]

  [[ 59  82 105]
   [ 82 105 128]]]]
(3, 2, 2, 3)


In [47]:
testMat1 = np.arange(1, 5).reshape((2, 2))
testMat2 = np.arange(1, 5).reshape((2, 2))

print(testMat1)
print(testMat2)

# 가능한 경우는 차원이 같을 때만!
# 같은 위치끼리 곱해 줌
print(testMat1 * testMat2)

# 꼭 .dot() 해줘야 제대로 계산 됨!
print(testMat1.dot(testMat2))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [56]:
# 인공지능 공부 순서
# 1. 선형대수 (가징 기본) - rank
#                       텐서 공부하려면 수리물리학 (아프켄, 보아스)
# 2. 통계학
# 3. 공업수학(라플라스 변환, 푸리에 변환)
# 4. 커스텀 라이브러리

In [57]:
# 실습!! #

from keras.models import Sequential
model = Sequential()

In [ ]:
from keras.layers import Dense
from keras.models import Sequential
input_shape = 20
units = 1
model.add(Dense(units, input_dim = input_shape))